// This file is generated by AppBuilder. Please do not edit manually.
// 
//



#include "app/framework/include/af.h"


void emAfCliBsendCommand(void);
void changeKeyCommand(void);
void emAfCliCountersCommand(void);
void emberAfPrintAllOff(void);
void emberAfPrintAllOn(void);
void printOffCommand(void);
void printOnCommand(void);
void emberAfPrintStatus(void);
void echoCommand(void);
void enableDisableEndpoint(void);
void endpointPrint(void);
void helpCommand(void);
void emAfCliInfoCommand(void);
void interpanCommand(void);
void interpanLongCommand(void);
void keysClearCommand(void);
void keysDeleteCommand(void);
void keysPrintCommand(void);
void printAllLibraryStatus(void);
void networkPermitJoinCommand(void);
void networkChangeChannelCommand(void);
void networkExtendedPanIdCommand(void);
void findJoinableNetworkCommand(void);
void findUnusedPanIdCommand(void);
void networkFormCommand(void);
void networkIdCommand(void);
void networkInitCommand(void);
void networkJoinCommand(void);
void networkLeaveCommand(void);
void networkRejoinCommand(void);
void networkSetCommand(void);
void optionAddressTablePrintCommand(void);
void optionAddressTableSetCommand(void);
void optionApsRetryCommand(void);
void optionBindingTableClearCommand(void);
void optionBindingTablePrintCommand(void);
void optionBindingTableSetCommand(void);
void optionDiscoverCommand(void);
void optionEndDeviceBindCommand(void);
void optionInstallCodeCommand(void);
void optionLinkCommand(void);
void optionPrintRxCommand(void);
void optionRegisterCommand(void);
void optionApsSecurityCommand(void);
void emberAfPluginAddressTableAddCommand(void);
void emberAfPluginAddressTableLookupCommand(void);
void emberAfPluginAddressTableRemoveCommand(void);
void emberAfPluginButtonJoiningButton0Command(void);
void emberAfPluginButtonJoiningButton1Command(void);
void emberAfPluginConcentratorAggregationCommand(void);
void emberAfPluginConcentratorPrintSourceRouteTable(void);
void emberAfPluginConcentratorStartDiscovery(void);
void emberAfPluginConcentratorStatus(void);
void emberAfPluginConcentratorStopDiscovery(void);
void emAfPluginIdentifyCliPrint(void);
#if defined(EMBER_TEST)
void emAfOtaLoadFileCommand(void);
#endif
void otaImageNotifyCommand(void);
void setPolicy(void);
void emAfOtaServerPolicyPrint(void);
void otaSendUpgradeCommand(void);
void emAfOtaStorageDataPrint(void);
void emAfOtaImageDelete(void);
void emAfOtaPrintAllImages(void);
void emAfOtaReloadStorageDevice(void);
void emAfOtaStorageInfoPrint(void);
void mode(void);
void print(void);
void respond(void);
void timeout(void);
void emAfPluginReportingCliAdd(void);
void emAfPluginReportingCliClear(void);
void emAfPluginReportingCliPrint(void);
void emAfPluginReportingCliRemove(void);
void printChildTable(void);
void printInfo(void);
void printNeighborTable(void);
void printRouteTable(void);
void emberAfPrintAttributeTable(void);
void printTimeCommand(void);
void emAfCliRawCommand(void);
void emAfCliReadCommand(void);
void resetCommand(void);
void getSetMfgToken(void);
void emAfCliSendCommand(void);
void emAfCliTimesyncCommand(void);
void emAfCliVersionCommand(void);
void emAfCliWriteCommand(void);
static void zclBasicRtfdCommand(void) {
  zclSimpleClientCommand( ZCL_BASIC_CLUSTER_ID,
                          ZCL_RESET_TO_FACTORY_DEFAULTS_COMMAND_ID);
}

static void zclColorcontrolEmovehueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_MOVE_HUE_COMMAND_ID);
}

static void zclColorcontrolEmovetohueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_MOVE_TO_HUE_COMMAND_ID);
}

static void zclColorcontrolEmovetohueandsatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_MOVE_TO_HUE_AND_SATURATION_COMMAND_ID);
}

static void zclColorcontrolEstephueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_ENHANCED_STEP_HUE_COMMAND_ID);
}

static void zclColorcontrolLoopCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_COLOR_LOOP_SET_COMMAND_ID);
}

static void zclColorcontrolMovecolorCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_COLOR_COMMAND_ID);
}

static void zclColorcontrolMovecolortempCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_COLOR_TEMPERATURE_COMMAND_ID);
}

static void zclColorcontrolMovehueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_HUE_COMMAND_ID);
}

static void zclColorcontrolMovesatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_SATURATION_COMMAND_ID);
}

static void zclColorcontrolMovetocolorCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_COLOR_COMMAND_ID);
}

static void zclColorcontrolMovetocolortempCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_COLOR_TEMPERATURE_COMMAND_ID);
}

static void zclColorcontrolMovetohueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_HUE_COMMAND_ID);
}

static void zclColorcontrolMovetohueandsatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_HUE_AND_SATURATION_COMMAND_ID);
}

static void zclColorcontrolMovetosatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_SATURATION_COMMAND_ID);
}

static void zclColorcontrolStepcolorCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_COLOR_COMMAND_ID);
}

static void zclColorcontrolStepcolortempCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_COLOR_TEMPERATUE_COMMAND_ID);
}

static void zclColorcontrolStephueCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_HUE_COMMAND_ID);
}

static void zclColorcontrolStepsatCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STEP_SATURATION_COMMAND_ID);
}

static void zclColorcontrolStopmovestepCommand(void) {
  zclSimpleClientCommand( ZCL_COLOR_CONTROL_CLUSTER_ID,
                          ZCL_STOP_MOVE_STEP_COMMAND_ID);
}

void zclGlobalDirectionCommand(void);
void zclGlobalCommandDiscoveryCommand(void);
void zclGlobalDiscoverCommand(void);
void zclGlobalExpectReportFromMeCommand(void);
void zclGlobalWriteCommand(void);
void zclGlobalReadCommand(void);
void zclGlobalReportCommand(void);
void zclGlobalReportReadCommand(void);
void zclGlobalSendMeAReportCommand(void);
static void zclGroupsAddCommand(void) {
  zclSimpleClientCommand( ZCL_GROUPS_CLUSTER_ID,
                          ZCL_ADD_GROUP_COMMAND_ID);
}

static void zclGroupsAddIfIdCommand(void) {
  zclSimpleClientCommand( ZCL_GROUPS_CLUSTER_ID,
                          ZCL_ADD_GROUP_IF_IDENTIFYING_COMMAND_ID);
}

void zclGroupsGetCommand(void);
static void zclGroupsRemoveCommand(void) {
  zclSimpleClientCommand( ZCL_GROUPS_CLUSTER_ID,
                          ZCL_REMOVE_GROUP_COMMAND_ID);
}

static void zclGroupsRmallCommand(void) {
  zclSimpleClientCommand( ZCL_GROUPS_CLUSTER_ID,
                          ZCL_REMOVE_ALL_GROUPS_COMMAND_ID);
}

static void zclGroupsViewCommand(void) {
  zclSimpleClientCommand( ZCL_GROUPS_CLUSTER_ID,
                          ZCL_VIEW_GROUP_COMMAND_ID);
}

static void zclIdentifyIdCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_COMMAND_ID);
}

void zclIdentifyOffCommand(void);
void zclIdentifyOnCommand(void);
static void zclIdentifyQueryCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_QUERY_COMMAND_ID);
}

static void zclIdentifyTriggerCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_TRIGGER_EFFECT_COMMAND_ID);
}

static void zclLevelControlMoveCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_COMMAND_ID);
}

static void zclLevelControlMvToLevelCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_LEVEL_COMMAND_ID);
}

static void zclLevelControlOMoveCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlOMvToLevelCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_MOVE_TO_LEVEL_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlOStepCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STEP_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlOStopCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STOP_WITH_ON_OFF_COMMAND_ID);
}

static void zclLevelControlStepCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STEP_COMMAND_ID);
}

static void zclLevelControlStopCommand(void) {
  zclSimpleClientCommand( ZCL_LEVEL_CONTROL_CLUSTER_ID,
                          ZCL_STOP_COMMAND_ID);
}

void zclMfgCodeCommand(void);
static void zclOnOffOffCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_OFF_COMMAND_ID);
}

static void zclOnOffOffeffectCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_OFF_WITH_EFFECT_COMMAND_ID);
}

static void zclOnOffOnCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_ON_COMMAND_ID);
}

static void zclOnOffOnrecallCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_ON_WITH_RECALL_GLOBAL_SCENE_COMMAND_ID);
}

static void zclOnOffOntimedoffCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_ON_WITH_TIMED_OFF_COMMAND_ID);
}

static void zclOnOffToggleCommand(void) {
  zclSimpleClientCommand( ZCL_ON_OFF_CLUSTER_ID,
                          ZCL_TOGGLE_COMMAND_ID);
}

static void zclPollControlLongCommand(void) {
  zclSimpleClientCommand( ZCL_POLL_CONTROL_CLUSTER_ID,
                          ZCL_SET_LONG_POLL_INTERVAL_COMMAND_ID);
}

static void zclPollControlShortCommand(void) {
  zclSimpleClientCommand( ZCL_POLL_CONTROL_CLUSTER_ID,
                          ZCL_SET_SHORT_POLL_INTERVAL_COMMAND_ID);
}

static void zclPollControlStopCommand(void) {
  zclSimpleClientCommand( ZCL_POLL_CONTROL_CLUSTER_ID,
                          ZCL_FAST_POLL_STOP_COMMAND_ID);
}

static void zclPowerProfileEnergyPhasesScheduleCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_ENERGY_PHASES_SCHEDULE_NOTIFICATION_COMMAND_ID);
}

static void zclPowerProfileEnergyPhasesScheduleStatesCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_ENERGY_PHASES_SCHEDULE_STATE_REQUEST_COMMAND_ID);
}

static void zclPowerProfileProfileCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_REQUEST_COMMAND_ID);
}

static void zclPowerProfileScheduleConstraintsCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_SCHEDULE_CONSTRAINTS_REQUEST_COMMAND_ID);
}

static void zclPowerProfileStateCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_STATE_REQUEST_COMMAND_ID);
}

static void zclScenesAddCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_ADD_SCENE_COMMAND_ID);
}

static void zclScenesCopyCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_COPY_SCENE_COMMAND_ID);
}

static void zclScenesEaddCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_ENHANCED_ADD_SCENE_COMMAND_ID);
}

static void zclScenesEviewCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_ENHANCED_VIEW_SCENE_COMMAND_ID);
}

static void zclScenesGetCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_GET_SCENE_MEMBERSHIP_COMMAND_ID);
}

static void zclScenesRecallCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_RECALL_SCENE_COMMAND_ID);
}

static void zclScenesRemoveCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_REMOVE_SCENE_COMMAND_ID);
}

static void zclScenesRmallCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_REMOVE_ALL_SCENES_COMMAND_ID);
}

static void zclScenesStoreCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_STORE_SCENE_COMMAND_ID);
}

static void zclScenesViewCommand(void) {
  zclSimpleClientCommand( ZCL_SCENES_CLUSTER_ID,
                          ZCL_VIEW_SCENE_COMMAND_ID);
}

static void zclSmFpCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_REQUEST_FAST_POLL_MODE_COMMAND_ID);
}

static void zclSmGpCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_PROFILE_COMMAND_ID);
}

void zclTestResponseOffCommand(void);
void zclTestResponseOnCommand(void);
void zclTimeCommand(void);
void zdoActiveEpCommand(void);
void zdoBindCommand(void);
void zdoIeeeAddressRequestCommand(void);
void zdoAddClusterCommand(void);
void zdoClearClusterCommand(void);
void zdoLeaveRequestCommand(void);
void zdoMatchCommand(void);
void zdoNodeCommand(void);
void zdoNwkAddressRequestCommand(void);
void zdoNetworkUpdateChannelCommand(void);
void zdoNetworkUpdateScanCommand(void);
void zdoNetworkUpdateSetCommand(void);
void zdoPowerDescriptorRequestCommand(void);
void zdoRouteRequestCommand(void);
void zdoSimpleCommand(void);
void zdoUnbindGroupCommand(void);
void zdoUnbindUnicastCommand(void);
PGM_P emberCommandTableInterpanShortCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};

PGM_P emberCommandTableInterpanLongCommandArguments[] = {
  "long ieee address to send the interpan message to",
  "two byte destination PA ID",
  "two byte destination profile ID",
  "two byte options",
  NULL
};

PGM_P emberCommandTableInterpanGroupCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};

EmberCommandEntry emberCommandTableInterpanCommands[] = {
  emberCommandEntryActionWithDetails("short", interpanCommand, "vvv", "Send an interpan message to a short id.", emberCommandTableInterpanShortCommandArguments),
  emberCommandEntryActionWithDetails("long", interpanLongCommand, "bvvv", "Send an interpan message to a long address (8 byte eui64)", emberCommandTableInterpanLongCommandArguments),
  emberCommandEntryActionWithDetails("group", interpanCommand, "vvv", "send an interpan message to a group id.", emberCommandTableInterpanGroupCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionApsretryCommands[] = {
  emberCommandEntryActionWithDetails("default", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("off", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("on", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P optionBindingTableSetCommandArguments[] = {
  "one byte index into the binding table",
  "cluster id to send with the discovery message",
  "local endpoint to bind",
  "remote endpoint to bind",
  "8 byte IEEE address provided big endian",
  NULL
};

EmberCommandEntry optionBindingTableCommands[] = {
  emberCommandEntryActionWithDetails("clear", optionBindingTableClearCommand, "", "Clear the binding table", NULL),
  emberCommandEntryActionWithDetails("set", optionBindingTableSetCommand, "uvuub", "Set a binding table entry for the arguments specified.", optionBindingTableSetCommandArguments),
  emberCommandEntryActionWithDetails("print", optionBindingTablePrintCommand, "", "Prints out the binding table to the command line.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionPrintRxMsgsCommands[] = {
  emberCommandEntryActionWithDetails("enable", optionPrintRxCommand, "", "Enable the printing of received messages.", NULL),
  emberCommandEntryActionWithDetails("disable", optionPrintRxCommand, "", "Disable the printing of received messages.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry securityApsCommands[] = {
  emberCommandEntryActionWithDetails("off", optionApsSecurityCommand, "", "Turns aps security off", NULL),
  emberCommandEntryActionWithDetails("on", optionApsSecurityCommand, "", "Turns aps security on", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry optionSecurityCommands[] = {
  emberCommandEntrySubMenu("aps", securityApsCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P optionAddressTableSetCommandArguments[] = {
  "one byte index into the address table",
  "IEEE address to enter into the address table",
  "two byte node id to enter into the address table",
  NULL
};

EmberCommandEntry optionAddressTableCommands[] = {
  emberCommandEntryActionWithDetails("set", optionAddressTableSetCommand, "ubv", "Set an entry in the address table according to the arguments specified", optionAddressTableSetCommandArguments),
  emberCommandEntryActionWithDetails("print", optionAddressTablePrintCommand, "", "Prints the address table.", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableOptionInstallCodeCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "install code including two-byte, little-endian CRC",
  NULL
};

PGM_P emberCommandTableOptionLinkCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "link key to enter into the table",
  NULL
};

PGM_P emberCommandTableOptionEdbCommandArguments[] = {
  "The local endpoint whose simple descriptor will be used to create the  ...",
  NULL
};

PGM_P emberCommandTableOptionDiscCommandArguments[] = {
  "the profile id to send with the discovery message",
  "cluster id to send with the discovery message",
  NULL
};

EmberCommandEntry emberCommandTableOptionCommands[] = {
  emberCommandEntryActionWithDetails("register", optionRegisterCommand, "", "Initiates Smart Energy Registration including Key Establishmen ...", NULL),
  emberCommandEntryActionWithDetails("install-code", optionInstallCodeCommand, "ubb", "Derives a link key from an install code and sets it in the link key ta ...", emberCommandTableOptionInstallCodeCommandArguments),
  emberCommandEntrySubMenu("address-table", optionAddressTableCommands, ""),
  emberCommandEntryActionWithDetails("link", optionLinkCommand, "ubb", "Sets a link key in the link key tabl ...", emberCommandTableOptionLinkCommandArguments),
  emberCommandEntrySubMenu("security", optionSecurityCommands, ""),
  emberCommandEntrySubMenu("print-rx-msgs", optionPrintRxMsgsCommands, ""),
  emberCommandEntrySubMenu("binding-table", optionBindingTableCommands, ""),
  emberCommandEntrySubMenu("apsretry", optionApsretryCommands, ""),
  emberCommandEntryActionWithDetails("edb", optionEndDeviceBindCommand, "u", "Sends a ZDO End Device Bind Request using the given local endpoint.", emberCommandTableOptionEdbCommandArguments),
  emberCommandEntryActionWithDetails("disc", optionDiscoverCommand, "vv", "Sends a ZDO Match Descriptor Request for the server side of the specif ...", emberCommandTableOptionDiscCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zdoNwkUpdChanCommandArguments[] = {
  "One byte channel to change to.",
  NULL
};

PGM_P zdoNwkUpdSetCommandArguments[] = {
  "Two byte network manager id",
  "Four byte channel mask",
  NULL
};

PGM_P zdoNwkUpdScanCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  NULL
};

EmberCommandEntry zdoNwkUpdCommands[] = {
  emberCommandEntryActionWithDetails("chan", zdoNetworkUpdateChannelCommand, "u", "Sends an update channel request.", zdoNwkUpdChanCommandArguments),
  emberCommandEntryActionWithDetails("set", zdoNetworkUpdateSetCommand, "vw", "Broadcasts the ID of the new network manager and active channels.", zdoNwkUpdSetCommandArguments),
  emberCommandEntryActionWithDetails("scan", zdoNetworkUpdateScanCommand, "vuv", "Performs an energy scan.", zdoNwkUpdScanCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zdoInClListAddCommandArguments[] = {
  "Array of two byte server cluster ids",
  NULL
};

EmberCommandEntry zdoInClListCommands[] = {
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of server (in) clusters.", NULL),
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "b", "Add clusters to the known server (in) clusters on this device.", zdoInClListAddCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry zdoOutClListCommands[] = {
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of client (out) clusters.", NULL),
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "", "Add clusters to the known client (out) clusters on this device.", NULL),
  emberCommandEntryTerminator()
};

PGM_P zdoUnbindUnicastCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The destination EUI64 in the binding (usually the local node's EUI64",
  "The destination endpoint of the binding",
  NULL
};

PGM_P zdoUnbindGroupCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The group address in the binding",
  NULL
};

EmberCommandEntry zdoUnbindCommands[] = {
  emberCommandEntryActionWithDetails("unicast", zdoUnbindUnicastCommand, "vbuvbu", "Sends an unbind request for a unicast binding to the target device.", zdoUnbindUnicastCommandArguments),
  emberCommandEntryActionWithDetails("group", zdoUnbindGroupCommand, "vbuvv", "Sends an unbind request for a multicast binding to the target device.", zdoUnbindGroupCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableZdoSimpleCommandArguments[] = {
  "Short address of the device where the simple descriptor request should ...",
  "The endpoint on the target device where the simple descriptor request  ...",
  NULL
};

PGM_P emberCommandTableZdoIeeeCommandArguments[] = {
  "Short address of the device for which a long address is requested",
  NULL
};

PGM_P emberCommandTableZdoNodeCommandArguments[] = {
  "Two byte address for the target device.",
  NULL
};

PGM_P emberCommandTableZdoNwkCommandArguments[] = {
  "IEEE address for which a short address is being requested",
  NULL
};

PGM_P emberCommandTableZdoLeaveCommandArguments[] = {
  "Target node ID",
  "Remove children",
  "Rejoin after leave",
  NULL
};

PGM_P emberCommandTableZdoRouteCommandArguments[] = {
  "Target node ID",
  "The index of the remote node's routing table to request.",
  NULL
};

PGM_P emberCommandTableZdoActiveCommandArguments[] = {
  "Two byte short id, destination for the active endpoint request",
  NULL
};

PGM_P emberCommandTableZdoPowerCommandArguments[] = {
  "Target node ID",
  NULL
};

PGM_P emberCommandTableZdoMatchCommandArguments[] = {
  "Two byte node id indicating wher",
  "Two byte profile id for the match descriptor request",
  NULL
};

PGM_P emberCommandTableZdoBindCommandArguments[] = {
  "Two byte destination node id",
  "Remote device's source endpoint to bind",
  "Remote endpoint to bind",
  "Cluster on which to bind",
  "Remote node EUI64",
  "Binding's dest EUI64.  Usually the local node's EUI64",
  NULL
};

EmberCommandEntry emberCommandTableZdoCommands[] = {
  emberCommandEntryActionWithDetails("simple", zdoSimpleCommand, "vu", "Sends out a simple descriptor request for the short address and endpoi ...", emberCommandTableZdoSimpleCommandArguments),
  emberCommandEntrySubMenu("unbind", zdoUnbindCommands, ""),
  emberCommandEntryActionWithDetails("ieee", zdoIeeeAddressRequestCommand, "v", "Request an ieee address based on a given node id.", emberCommandTableZdoIeeeCommandArguments),
  emberCommandEntryActionWithDetails("node", zdoNodeCommand, "v", "Sends a node descriptor request to a given target device", emberCommandTableZdoNodeCommandArguments),
  emberCommandEntryActionWithDetails("nwk", zdoNwkAddressRequestCommand, "b", "Sends a network address request for the given IEEE address.", emberCommandTableZdoNwkCommandArguments),
  emberCommandEntrySubMenu("out-cl-list", zdoOutClListCommands, ""),
  emberCommandEntryActionWithDetails("leave", zdoLeaveRequestCommand, "vuu", "Send a ZDO Management Leave command to the target device.", emberCommandTableZdoLeaveCommandArguments),
  emberCommandEntryActionWithDetails("route", zdoRouteRequestCommand, "vu", "Send a ZDO route request command to the target.", emberCommandTableZdoRouteCommandArguments),
  emberCommandEntryActionWithDetails("active", zdoActiveEpCommand, "v", "Send an active endpoint request to the device with the given short id.", emberCommandTableZdoActiveCommandArguments),
  emberCommandEntryActionWithDetails("power", zdoPowerDescriptorRequestCommand, "v", "Send a ZDO Power Descriptor Request to the target device.", emberCommandTableZdoPowerCommandArguments),
  emberCommandEntryActionWithDetails("match", zdoMatchCommand, "vv", "Sends a matchDescriptorsRequest to the given destination with the give ...", emberCommandTableZdoMatchCommandArguments),
  emberCommandEntryActionWithDetails("bind", zdoBindCommand, "vuuvbb", "Send a ZDO Bind command to a device specified in the command arguments ...", emberCommandTableZdoBindCommandArguments),
  emberCommandEntrySubMenu("in-cl-list", zdoInClListCommands, ""),
  emberCommandEntrySubMenu("nwk-upd", zdoNwkUpdCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableChangekeyLinkCommandArguments[] = {
  "The link key provided as a 16 byte array",
  NULL
};

PGM_P emberCommandTableChangekeyNetworkCommandArguments[] = {
  "The network key provided as a 16 byte array",
  NULL
};

EmberCommandEntry emberCommandTableChangekeyCommands[] = {
  emberCommandEntryActionWithDetails("link", changeKeyCommand, "b", "Change the link key to the one provided in the 16 byte array argument  ...", emberCommandTableChangekeyLinkCommandArguments),
  emberCommandEntryActionWithDetails("network", changeKeyCommand, "b", "Change the network key to the 16 byte array provided as an argument to ...", emberCommandTableChangekeyNetworkCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclPollControlShortCommandArguments[] = {
  "",
  NULL
};

PGM_P zclPollControlLongCommandArguments[] = {
  "",
  NULL
};

EmberCommandEntry zclPollControlCommands[] = {
  emberCommandEntryActionWithDetails("short", zclPollControlShortCommand, "v", "The Set Short Poll Interval command is used to set the read only Short ...", zclPollControlShortCommandArguments),
  emberCommandEntryActionWithDetails("stop", zclPollControlStopCommand, "", "The Fast Poll Stop command is used to stop the fast poll mode initiate ...", NULL),
  emberCommandEntryActionWithDetails("long", zclPollControlLongCommand, "w", "The Set Long Poll Interval command is used to set the read only Long P ...", zclPollControlLongCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclGroupsAddIfIdCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclGroupsRemoveCommandArguments[] = {
  "",
  NULL
};

PGM_P zclGroupsGetCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclGroupsViewCommandArguments[] = {
  "",
  NULL
};

PGM_P zclGroupsAddCommandArguments[] = {
  "",
  "",
  NULL
};

EmberCommandEntry zclGroupsCommands[] = {
  emberCommandEntryActionWithDetails("add-if-id", zclGroupsAddIfIdCommand, "vb", "Command description for AddGroupIfIdentifying", zclGroupsAddIfIdCommandArguments),
  emberCommandEntryActionWithDetails("remove", zclGroupsRemoveCommand, "v", "Command description for RemoveGroup", zclGroupsRemoveCommandArguments),
  emberCommandEntryActionWithDetails("get", zclGroupsGetCommand, "uv*", "Command description for GetGroupMembership", zclGroupsGetCommandArguments),
  emberCommandEntryActionWithDetails("rmall", zclGroupsRmallCommand, "", "Command description for RemoveAllGroups", NULL),
  emberCommandEntryActionWithDetails("view", zclGroupsViewCommand, "v", "Command description for ViewGroup", zclGroupsViewCommandArguments),
  emberCommandEntryActionWithDetails("add", zclGroupsAddCommand, "vb", "Command description for AddGroup", zclGroupsAddCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclScenesStoreCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclScenesRemoveCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclScenesGetCommandArguments[] = {
  "",
  NULL
};

PGM_P zclScenesRmallCommandArguments[] = {
  "",
  NULL
};

PGM_P zclScenesRecallCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclScenesEaddCommandArguments[] = {
  "",
  "",
  "",
  "",
  "",
  NULL
};

PGM_P zclScenesViewCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclScenesEviewCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclScenesAddCommandArguments[] = {
  "",
  "",
  "",
  "",
  "",
  NULL
};

PGM_P zclScenesCopyCommandArguments[] = {
  "",
  "",
  "",
  "",
  "",
  NULL
};

EmberCommandEntry zclScenesCommands[] = {
  emberCommandEntryActionWithDetails("store", zclScenesStoreCommand, "vu", "Command description for StoreScene", zclScenesStoreCommandArguments),
  emberCommandEntryActionWithDetails("remove", zclScenesRemoveCommand, "vu", "Command description for RemoveScene", zclScenesRemoveCommandArguments),
  emberCommandEntryActionWithDetails("get", zclScenesGetCommand, "v", "Command description for GetSceneMembership", zclScenesGetCommandArguments),
  emberCommandEntryActionWithDetails("rmall", zclScenesRmallCommand, "v", "Command description for RemoveAllScenes", zclScenesRmallCommandArguments),
  emberCommandEntryActionWithDetails("recall", zclScenesRecallCommand, "vu", "Command description for RecallScene", zclScenesRecallCommandArguments),
  emberCommandEntryActionWithDetails("eadd", zclScenesEaddCommand, "vuvbw*", "Command description for EnhancedAddScene", zclScenesEaddCommandArguments),
  emberCommandEntryActionWithDetails("view", zclScenesViewCommand, "vu", "Command description for ViewScene", zclScenesViewCommandArguments),
  emberCommandEntryActionWithDetails("eview", zclScenesEviewCommand, "vu", "Command description for EnhancedViewScene", zclScenesEviewCommandArguments),
  emberCommandEntryActionWithDetails("add", zclScenesAddCommand, "vuvbw*", "Add a scene to the scene tabl ...", zclScenesAddCommandArguments),
  emberCommandEntryActionWithDetails("copy", zclScenesCopyCommand, "uvuvu", "Command description for CopyScene", zclScenesCopyCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry zclBasicCommands[] = {
  emberCommandEntryActionWithDetails("rtfd", zclBasicRtfdCommand, "", "Command that resets all attribute values to factory default.", NULL),
  emberCommandEntryTerminator()
};

PGM_P zclLevelControlOMoveCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclLevelControlMvToLevelCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclLevelControlOStepCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclLevelControlOMvToLevelCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclLevelControlStepCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclLevelControlMoveCommandArguments[] = {
  "",
  "",
  NULL
};

EmberCommandEntry zclLevelControlCommands[] = {
  emberCommandEntryActionWithDetails("stop", zclLevelControlStopCommand, "", "Command description for Stop", NULL),
  emberCommandEntryActionWithDetails("o-move", zclLevelControlOMoveCommand, "uu", "Command description for MoveWithOnOff", zclLevelControlOMoveCommandArguments),
  emberCommandEntryActionWithDetails("o-stop", zclLevelControlOStopCommand, "", "Command description for StopWithOnOff", NULL),
  emberCommandEntryActionWithDetails("mv-to-level", zclLevelControlMvToLevelCommand, "uv", "Command description for MoveToLevel", zclLevelControlMvToLevelCommandArguments),
  emberCommandEntryActionWithDetails("o-step", zclLevelControlOStepCommand, "uuv", "Command description for StepWithOnOff", zclLevelControlOStepCommandArguments),
  emberCommandEntryActionWithDetails("o-mv-to-level", zclLevelControlOMvToLevelCommand, "uv", "Command description for MoveToLevelWithOnOff", zclLevelControlOMvToLevelCommandArguments),
  emberCommandEntryActionWithDetails("step", zclLevelControlStepCommand, "uuv", "Command description for Step", zclLevelControlStepCommandArguments),
  emberCommandEntryActionWithDetails("move", zclLevelControlMoveCommand, "uu", "Command description for Move", zclLevelControlMoveCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclGlobalExpectReportFromMeCommandArguments[] = {
  "The cluster id for the requested report.",
  "The attribute id for the requested report.",
  "Maximum amount of time between reports.",
  NULL
};

PGM_P zclGlobalDiscComGenCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};

PGM_P zclGlobalUwriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P zclGlobalDiscComRecCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};

PGM_P zclGlobalDirectionCommandArguments[] = {
  "The direction for global commands, 0 = client to server, 1 = server to ...",
  NULL
};

PGM_P zclGlobalSendMeAReportCommandArguments[] = {
  "The cluster id of the requested report.",
  "The attribute id for requested report.",
  "The two byte ZigBee type value for the requested report.",
  "Minimum number of seconds between reports.",
  "Maximum number of seconds between reports.",
  "Amount of change to trigger a report.",
  NULL
};

PGM_P zclGlobalWriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P zclGlobalReportReadCommandArguments[] = {
  "The cluster id to read from.",
  "The attribute id to read from.",
  "0 for client-to-server, 1 for server-to-client.",
  NULL
};

PGM_P zclGlobalReportCommandArguments[] = {
  "The desired endpoint.",
  "The cluster id.",
  "The attribute id.",
  "The mask.",
  NULL
};

PGM_P zclGlobalNwriteCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};

PGM_P zclGlobalDiscoverCommandArguments[] = {
  "The cluster id of the cluster to discover.",
  "The attribute id of the attribute to read during discovery.",
  "Max number of discovery responses.",
  NULL
};

PGM_P zclGlobalReadCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  NULL
};

EmberCommandEntry zclGlobalCommands[] = {
  emberCommandEntryActionWithDetails("expect-report-from-me", zclGlobalExpectReportFromMeCommand, "vvv", "Create a expect-report-from-me message with associated values.", zclGlobalExpectReportFromMeCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-gen", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Generated command with associated values.", zclGlobalDiscComGenCommandArguments),
  emberCommandEntryActionWithDetails("uwrite", zclGlobalWriteCommand, "vvub", "Creates a global write undivided command message to write to the clust ...", zclGlobalUwriteCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-rec", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Received command with associated values.", zclGlobalDiscComRecCommandArguments),
  emberCommandEntryActionWithDetails("direction", zclGlobalDirectionCommand, "u", "Sets the direction for global commands, either client to server or ser ...", zclGlobalDirectionCommandArguments),
  emberCommandEntryActionWithDetails("send-me-a-report", zclGlobalSendMeAReportCommand, "vvuvvb", "Creates a global send me a report command for the associated values.", zclGlobalSendMeAReportCommandArguments),
  emberCommandEntryActionWithDetails("write", zclGlobalWriteCommand, "vvwb", "Creates a global write command message to write to the cluster and att ...", zclGlobalWriteCommandArguments),
  emberCommandEntryActionWithDetails("report-read", zclGlobalReportReadCommand, "vvu", "Creates a global read reporting command for the associated cluster, at ...", zclGlobalReportReadCommandArguments),
  emberCommandEntryActionWithDetails("report", zclGlobalReportCommand, "uvvu", "", zclGlobalReportCommandArguments),
  emberCommandEntryActionWithDetails("nwrite", zclGlobalWriteCommand, "vvub", "Creates a global write command message to write to the cluster and att ...", zclGlobalNwriteCommandArguments),
  emberCommandEntryActionWithDetails("discover", zclGlobalDiscoverCommand, "vvu", "Creates discovery message for devices with the associated cluster and  ...", zclGlobalDiscoverCommandArguments),
  emberCommandEntryActionWithDetails("read", zclGlobalReadCommand, "vv", "Creates a global read command message to read from the cluster and att ...", zclGlobalReadCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclColorcontrolStepsatCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovehueCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovecolorCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovetosatCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovetocolortempCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclColorcontrolStepcolorCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovetohueandsatCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolStepcolortempCommandArguments[] = {
  "",
  "",
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolStephueCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolEstephueCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovecolortempCommandArguments[] = {
  "",
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovesatCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovetocolorCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolLoopCommandArguments[] = {
  "",
  "",
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolMovetohueCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolEmovehueCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclColorcontrolEmovetohueandsatCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclColorcontrolEmovetohueCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

EmberCommandEntry zclColorcontrolCommands[] = {
  emberCommandEntryActionWithDetails("stepsat", zclColorcontrolStepsatCommand, "uuu", "Step saturation up or down by specified size at specified rate.", zclColorcontrolStepsatCommandArguments),
  emberCommandEntryActionWithDetails("movehue", zclColorcontrolMovehueCommand, "uu", "Move hue up or down at specified rate.", zclColorcontrolMovehueCommandArguments),
  emberCommandEntryActionWithDetails("movecolor", zclColorcontrolMovecolorCommand, "00", "Moves the color.", zclColorcontrolMovecolorCommandArguments),
  emberCommandEntryActionWithDetails("movetosat", zclColorcontrolMovetosatCommand, "uv", "Move to specified saturation.", zclColorcontrolMovetosatCommandArguments),
  emberCommandEntryActionWithDetails("movetocolortemp", zclColorcontrolMovetocolortempCommand, "vv", "Moves the lighting to a specific color temperature.", zclColorcontrolMovetocolortempCommandArguments),
  emberCommandEntryActionWithDetails("stepcolor", zclColorcontrolStepcolorCommand, "00v", "Steps the lighting to a specific color.", zclColorcontrolStepcolorCommandArguments),
  emberCommandEntryActionWithDetails("movetohueandsat", zclColorcontrolMovetohueandsatCommand, "uuv", "Move to hue and saturation.", zclColorcontrolMovetohueandsatCommandArguments),
  emberCommandEntryActionWithDetails("stepcolortemp", zclColorcontrolStepcolortempCommand, "uvvvv", "Command description for StepColorTemperatue", zclColorcontrolStepcolortempCommandArguments),
  emberCommandEntryActionWithDetails("stephue", zclColorcontrolStephueCommand, "uuu", "Step hue up or down by specified size at specified rate.", zclColorcontrolStephueCommandArguments),
  emberCommandEntryActionWithDetails("estephue", zclColorcontrolEstephueCommand, "uvv", "Command description for EnhancedStepHue", zclColorcontrolEstephueCommandArguments),
  emberCommandEntryActionWithDetails("movecolortemp", zclColorcontrolMovecolortempCommand, "uvvv", "Command description for MoveColorTemperature", zclColorcontrolMovecolortempCommandArguments),
  emberCommandEntryActionWithDetails("movesat", zclColorcontrolMovesatCommand, "uu", "Move saturation up or down at specified rate.", zclColorcontrolMovesatCommandArguments),
  emberCommandEntryActionWithDetails("movetocolor", zclColorcontrolMovetocolorCommand, "vvv", "Move to specified color.", zclColorcontrolMovetocolorCommandArguments),
  emberCommandEntryActionWithDetails("loop", zclColorcontrolLoopCommand, "uuuvv", "Command description for ColorLoopSet", zclColorcontrolLoopCommandArguments),
  emberCommandEntryActionWithDetails("movetohue", zclColorcontrolMovetohueCommand, "uuv", "Move to specified hue.", zclColorcontrolMovetohueCommandArguments),
  emberCommandEntryActionWithDetails("emovehue", zclColorcontrolEmovehueCommand, "uv", "Command description for EnhancedMoveHue", zclColorcontrolEmovehueCommandArguments),
  emberCommandEntryActionWithDetails("emovetohueandsat", zclColorcontrolEmovetohueandsatCommand, "vuv", "Command description for EnhancedMoveToHueAndSaturation", zclColorcontrolEmovetohueandsatCommandArguments),
  emberCommandEntryActionWithDetails("stopmovestep", zclColorcontrolStopmovestepCommand, "", "Command description for StopMoveStep", NULL),
  emberCommandEntryActionWithDetails("emovetohue", zclColorcontrolEmovetohueCommand, "vuv", "Command description for EnhancedMoveToHue", zclColorcontrolEmovetohueCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclOnOffOffeffectCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclOnOffOntimedoffCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

EmberCommandEntry zclOnOffCommands[] = {
  emberCommandEntryActionWithDetails("offeffect", zclOnOffOffeffectCommand, "uu", "Command description for OffWithEffect", zclOnOffOffeffectCommandArguments),
  emberCommandEntryActionWithDetails("toggle", zclOnOffToggleCommand, "", "Command description for Toggle", NULL),
  emberCommandEntryActionWithDetails("onrecall", zclOnOffOnrecallCommand, "", "Command description for OnWithRecallGlobalScene", NULL),
  emberCommandEntryActionWithDetails("off", zclOnOffOffCommand, "", "Command description for Off", NULL),
  emberCommandEntryActionWithDetails("on", zclOnOffOnCommand, "", "Command description for On", NULL),
  emberCommandEntryActionWithDetails("ontimedoff", zclOnOffOntimedoffCommand, "uvv", "Command description for OnWithTimedOff", zclOnOffOntimedoffCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclIdentifyIdCommandArguments[] = {
  "",
  NULL
};

PGM_P zclIdentifyTriggerCommandArguments[] = {
  "",
  "",
  NULL
};

PGM_P zclIdentifyOffCommandArguments[] = {
  "The endpoint on which to stop identifying",
  NULL
};

PGM_P zclIdentifyOnCommandArguments[] = {
  "The endpoint on the device which should begin identifying",
  "The number of seconds to spend identifying",
  NULL
};

EmberCommandEntry zclIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("id", zclIdentifyIdCommand, "v", "Command description for Identify", zclIdentifyIdCommandArguments),
  emberCommandEntryActionWithDetails("trigger", zclIdentifyTriggerCommand, "uu", "Command description for TriggerEffect", zclIdentifyTriggerCommandArguments),
  emberCommandEntryActionWithDetails("query", zclIdentifyQueryCommand, "", "Command description for IdentifyQuery", NULL),
  emberCommandEntryActionWithDetails("off", zclIdentifyOffCommand, "u", "Creates a message payload for a command that turns identifying off on  ...", zclIdentifyOffCommandArguments),
  emberCommandEntryActionWithDetails("on", zclIdentifyOnCommand, "uv", "Creates the payload for an over the air message that turns identifying ...", zclIdentifyOnCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P zclPowerProfileScheduleConstraintsCommandArguments[] = {
  "",
  NULL
};

PGM_P zclPowerProfileEnergyPhasesScheduleCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclPowerProfileProfileCommandArguments[] = {
  "",
  NULL
};

PGM_P zclPowerProfileEnergyPhasesScheduleStatesCommandArguments[] = {
  "",
  NULL
};

EmberCommandEntry zclPowerProfileCommands[] = {
  emberCommandEntryActionWithDetails("schedule-constraints", zclPowerProfileScheduleConstraintsCommand, "u", "The PowerProfileScheduleConstraintsRequest Command is generated by a d ...", zclPowerProfileScheduleConstraintsCommandArguments),
  emberCommandEntryActionWithDetails("state", zclPowerProfileStateCommand, "", "The PowerProfileStateRequest Command is generated in order to retrieve ...", NULL),
  emberCommandEntryActionWithDetails("energy-phases-schedule", zclPowerProfileEnergyPhasesScheduleCommand, "uub*", "The EnergyPhasesScheduleNotification Command is generated by a device  ...", zclPowerProfileEnergyPhasesScheduleCommandArguments),
  emberCommandEntryActionWithDetails("profile", zclPowerProfileProfileCommand, "u", "The PowerProfileRequest Command is generated by a device supporting th ...", zclPowerProfileProfileCommandArguments),
  emberCommandEntryActionWithDetails("energy-phases-schedule-states", zclPowerProfileEnergyPhasesScheduleStatesCommand, "u", "The EnergyPhasesScheduleStateRequest  Command is generated by a device ...", zclPowerProfileEnergyPhasesScheduleStatesCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry testResponseCommands[] = {
  emberCommandEntryActionWithDetails("off", zclTestResponseOffCommand, "", "Sets a flag so that the application framework WILL NOT respond to the  ...", NULL),
  emberCommandEntryActionWithDetails("on", zclTestResponseOnCommand, "", "Sets a flag so that the application framework WILL respond to the next ...", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry zclTestCommands[] = {
  emberCommandEntrySubMenu("response", testResponseCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P zclSmGpCommandArguments[] = {
  "",
  "",
  "",
  NULL
};

PGM_P zclSmFpCommandArguments[] = {
  "",
  "",
  NULL
};

EmberCommandEntry zclSmCommands[] = {
  emberCommandEntryActionWithDetails("gp", zclSmGpCommand, "uwu", "Command description for GetProfile", zclSmGpCommandArguments),
  emberCommandEntryActionWithDetails("fp", zclSmFpCommand, "uu", "Command to request fast poll mode.", zclSmFpCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableZclTimeCommandArguments[] = {
  "ZigBee UTC time, number of seconds since the year 2000",
  NULL
};

PGM_P emberCommandTableZclMfgCodeCommandArguments[] = {
  "Manufacturer Specific Id",
  NULL
};

EmberCommandEntry emberCommandTableZclCommands[] = {
  emberCommandEntrySubMenu("sm", zclSmCommands, ""),
  emberCommandEntrySubMenu("test", zclTestCommands, ""),
  emberCommandEntrySubMenu("power-profile", zclPowerProfileCommands, ""),
  emberCommandEntrySubMenu("identify", zclIdentifyCommands, ""),
  emberCommandEntrySubMenu("on-off", zclOnOffCommands, ""),
  emberCommandEntrySubMenu("colorcontrol", zclColorcontrolCommands, ""),
  emberCommandEntrySubMenu("global", zclGlobalCommands, ""),
  emberCommandEntrySubMenu("level-control", zclLevelControlCommands, ""),
  emberCommandEntryActionWithDetails("time", zclTimeCommand, "w", "Cli command to call emberAfSetTime function documented in af.h", emberCommandTableZclTimeCommandArguments),
  emberCommandEntrySubMenu("basic", zclBasicCommands, ""),
  emberCommandEntrySubMenu("scenes", zclScenesCommands, ""),
  emberCommandEntryActionWithDetails("mfg-code", zclMfgCodeCommand, "v", "Sets the two byte manufacturer specific identifier to use for the next ...", emberCommandTableZclMfgCodeCommandArguments),
  emberCommandEntrySubMenu("groups", zclGroupsCommands, ""),
  emberCommandEntrySubMenu("poll-control", zclPollControlCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableDebugprintOffCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};

PGM_P emberCommandTableDebugprintOnCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};

EmberCommandEntry emberCommandTableDebugprintCommands[] = {
  emberCommandEntryActionWithDetails("status", emberAfPrintStatus, "", "Prints out the current settings for debug printing on the device", NULL),
  emberCommandEntryActionWithDetails("all_off", emberAfPrintAllOff, "", "Turns off all debug printing", NULL),
  emberCommandEntryActionWithDetails("off", printOffCommand, "u", "Turns off compiled in debug printing for a specific debug printing are ...", emberCommandTableDebugprintOffCommandArguments),
  emberCommandEntryActionWithDetails("on", printOnCommand, "u", "Turns on compiled in debug printing for a specific debug printing area ...", emberCommandTableDebugprintOnCommandArguments),
  emberCommandEntryActionWithDetails("all_on", emberAfPrintAllOn, "", "Turns on all compiled in debug printing", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry networkFindCommands[] = {
  emberCommandEntryActionWithDetails("joinable", findJoinableNetworkCommand, "", "Begins a search for a joinable networ ...", NULL),
  emberCommandEntryActionWithDetails("unused", findUnusedPanIdCommand, "", "Begins a search for an unused Channel and Pan I ...", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableNetworkExtpanidCommandArguments[] = {
  "The bytes for the extended pan id",
  NULL
};

PGM_P emberCommandTableNetworkBroadPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};

PGM_P emberCommandTableNetworkFormCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};

PGM_P emberCommandTableNetworkChangeChannelCommandArguments[] = {
  "The channel to change to.",
  NULL
};

PGM_P emberCommandTableNetworkSetCommandArguments[] = {
  "The network index to use for CLI commands",
  NULL
};

PGM_P emberCommandTableNetworkJoinCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};

PGM_P emberCommandTableNetworkPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};

PGM_P emberCommandTableNetworkRejoinCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  NULL
};

EmberCommandEntry emberCommandTableNetworkCommands[] = {
  emberCommandEntryActionWithDetails("id", networkIdCommand, "", "Prints the current Node ID, EUI64, and Pan ID.", NULL),
  emberCommandEntryActionWithDetails("extpanid", networkExtendedPanIdCommand, "b", "Write the extended pan id for the device.", emberCommandTableNetworkExtpanidCommandArguments),
  emberCommandEntryActionWithDetails("broad-pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds AND broadc ...", emberCommandTableNetworkBroadPjoinCommandArguments),
  emberCommandEntryActionWithDetails("leave", networkLeaveCommand, "", "Leave the current network.", NULL),
  emberCommandEntryActionWithDetails("form", networkFormCommand, "usv", "Create a network on the given channel, power and panId.", emberCommandTableNetworkFormCommandArguments),
  emberCommandEntryActionWithDetails("change-channel", networkChangeChannelCommand, "u", "Attempts to change device over to a different channel given in the cha ...", emberCommandTableNetworkChangeChannelCommandArguments),
  emberCommandEntryActionWithDetails("set", networkSetCommand, "u", "Set the network index used by all future CLI command ...", emberCommandTableNetworkSetCommandArguments),
  emberCommandEntryActionWithDetails("init", networkInitCommand, "", "Initialize a network; this is a test command used for tc-swap-out test ...", NULL),
  emberCommandEntryActionWithDetails("join", networkJoinCommand, "usv", "Join an existing network on the given channel, power and panId.", emberCommandTableNetworkJoinCommandArguments),
  emberCommandEntryActionWithDetails("pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds", emberCommandTableNetworkPjoinCommandArguments),
  emberCommandEntrySubMenu("find", networkFindCommands, ""),
  emberCommandEntryActionWithDetails("rejoin", networkRejoinCommand, "uw", "Rejoin an existing network in a secure or insecure manner.", emberCommandTableNetworkRejoinCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableEndpointEnableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};

PGM_P emberCommandTableEndpointDisableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};

EmberCommandEntry emberCommandTableEndpointCommands[] = {
  emberCommandEntryActionWithDetails("enable", enableDisableEndpoint, "u", "Enable the endpoint for processing ZCL messages.", emberCommandTableEndpointEnableCommandArguments),
  emberCommandEntryActionWithDetails("disable", enableDisableEndpoint, "u", "Disable the endpoint for processing ZCL messages.", emberCommandTableEndpointDisableCommandArguments),
  emberCommandEntryActionWithDetails("print", endpointPrint, "", "Print the status of all the endpoints.", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginOtaStorageCommonDataPrintCommandArguments[] = {
  "The index of the image to print its data.",
  "The offset into the OTA image that will be printed.",
  NULL
};

PGM_P pluginOtaStorageCommonDeleteCommandArguments[] = {
  "The index at which to begin bootloading the image",
  NULL
};

EmberCommandEntry pluginOtaStorageCommonCommands[] = {
  emberCommandEntryActionWithDetails("data-print", emAfOtaStorageDataPrint, "uw", "Print arbitray bytes of the OTA image on disk.", pluginOtaStorageCommonDataPrintCommandArguments),
  emberCommandEntryActionWithDetails("storage-info", emAfOtaStorageInfoPrint, "", "Print information about the storage device.", NULL),
  emberCommandEntryActionWithDetails("printImages", emAfOtaPrintAllImages, "", "Prints the images.", NULL),
  emberCommandEntryActionWithDetails("delete", emAfOtaImageDelete, "u", "Deletes the image at the specified index.", pluginOtaStorageCommonDeleteCommandArguments),
  emberCommandEntryActionWithDetails("reload", emAfOtaReloadStorageDevice, "", "Reload the storage device.", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginPollControlClientRespondCommandArguments[] = {
  "The response mode.",
  NULL
};

PGM_P pluginPollControlClientTimeoutCommandArguments[] = {
  "The fast polling timeout.",
  NULL
};

PGM_P pluginPollControlClientModeCommandArguments[] = {
  "The fast polling mode.",
  NULL
};

EmberCommandEntry pluginPollControlClientCommands[] = {
  emberCommandEntryActionWithDetails("respond", respond, "u", "Set the response mode.", pluginPollControlClientRespondCommandArguments),
  emberCommandEntryActionWithDetails("timeout", timeout, "v", "Set the fast polling timeout.", pluginPollControlClientTimeoutCommandArguments),
  emberCommandEntryActionWithDetails("print", print, "", "Print the fast polling mode and timeout.", NULL),
  emberCommandEntryActionWithDetails("mode", mode, "u", "Set the fast polling mode.", pluginPollControlClientModeCommandArguments),
  emberCommandEntryTerminator()
};

PGM_P pluginReportingRemoveCommandArguments[] = {
  "The index of the report to be removed.",
  NULL
};

PGM_P pluginReportingAddCommandArguments[] = {
  "The local endpoint from which the attribute is reported.",
  "The cluster where the attribute is located.",
  "The id of the attribute being reported.",
  "0 for client-side attributes or 1 for server-side attributes.",
  "The minimum reporting interval, measured in seconds.",
  "The maximum reporting interval, measured in seconds.",
  "The minimum change to the attribute that will result in a report being ...",
  NULL
};

EmberCommandEntry pluginReportingCommands[] = {
  emberCommandEntryActionWithDetails("clear", emAfPluginReportingCliClear, "", "Clear all entries from the report table.", NULL),
  emberCommandEntryActionWithDetails("remove", emAfPluginReportingCliRemove, "u", "Remove an entry from the report table.", pluginReportingRemoveCommandArguments),
  emberCommandEntryActionWithDetails("add", emAfPluginReportingCliAdd, "uvvuvvw", "Add a new entry to the report table.", pluginReportingAddCommandArguments),
  emberCommandEntryActionWithDetails("print", emAfPluginReportingCliPrint, "", "Print the report table.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginButtonJoiningCommands[] = {
  emberCommandEntryActionWithDetails("button1", emberAfPluginButtonJoiningButton1Command, "", "Simulate a depression of button 1.", NULL),
  emberCommandEntryActionWithDetails("button0", emberAfPluginButtonJoiningButton0Command, "", "Simulate a depression of button 0.", NULL),
  emberCommandEntryTerminator()
};

PGM_P otaServerPolicyUpgradeCommandArguments[] = {
  "0: Upgrade Now (default), 1: Upgrade in 2       minutes, 2: Ask me lat ...",
  NULL
};

PGM_P otaServerPolicyImageReqMinPeriodCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P otaServerPolicyQueryCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P otaServerPolicyPageReqMissCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P otaServerPolicyPageReqSupCommandArguments[] = {
  "0: Upgrade if server has newer (default), 1: Downgrade if server has o ...",
  NULL
};

PGM_P otaServerPolicyBlockRequestCommandArguments[] = {
  "0: Send block (default), 1: Delay download once for 2 minutes, 2: Alwa ...",
  NULL
};

EmberCommandEntry otaServerPolicyCommands[] = {
  emberCommandEntryActionWithDetails("upgrade", setPolicy, "u", "Sets the policy used by the OTA Server Policy Plugin when it receives  ...", otaServerPolicyUpgradeCommandArguments),
  emberCommandEntryActionWithDetails("image-req-min-period", setPolicy, "u", "", otaServerPolicyImageReqMinPeriodCommandArguments),
  emberCommandEntryActionWithDetails("query", setPolicy, "u", "Sets the policy used by the OTA Server Policy Plugin when it receives  ...", otaServerPolicyQueryCommandArguments),
  emberCommandEntryActionWithDetails("page-req-miss", setPolicy, "u", "", otaServerPolicyPageReqMissCommandArguments),
  emberCommandEntryActionWithDetails("page-req-sup", setPolicy, "u", "", otaServerPolicyPageReqSupCommandArguments),
  emberCommandEntryActionWithDetails("blockRequest", setPolicy, "u", "Sets the policy used by the ota-server Policy Plugin when it receives  ...", otaServerPolicyBlockRequestCommandArguments),
  emberCommandEntryActionWithDetails("print", emAfOtaServerPolicyPrint, "", "Prints the polices used by the OTA Server Policy Plugin", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginOtaServerUpgradeCommandArguments[] = {
  "device id for the image",
  "software version for the image",
  NULL
};

PGM_P pluginOtaServerNotifyCommandArguments[] = {
  "The node ID (can be a broadcast address) to which this OTA Notify mess ...",
  "Target endpoint for the OTA Notify message (only really meaningful for ...",
  "Used to specify which parameters you want included in the OTA Notify c ...",
  "Corresponds to QueryJitter parameter in the OTA Upgrade cluster specif ...",
  "Manufacturer ID for the image being advertised (should match the mfr I ...",
  "Image type ID for the image being advertised (should match the image t ...",
  "Firmware version of the image being advertised (should match the versi ...",
  NULL
};

PGM_P pluginOtaServerLoadFileCommandArguments[] = {
  "The file name.",
  NULL
};

EmberCommandEntry pluginOtaServerCommands[] = {
  emberCommandEntryActionWithDetails("upgrade", otaSendUpgradeCommand, "vu", "Instruct a device to upgrade now.", pluginOtaServerUpgradeCommandArguments),
  emberCommandEntryActionWithDetails("notify", otaImageNotifyCommand, "vuuuvvv", "Sends an OTA Image Notify message to the specified destination indicat ...", pluginOtaServerNotifyCommandArguments),
#if defined(EMBER_TEST)
  emberCommandEntryActionWithDetails("load-file", emAfOtaLoadFileCommand, "b", "Load file.", pluginOtaServerLoadFileCommandArguments),
#endif
  emberCommandEntrySubMenu("policy", otaServerPolicyCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginStackDiagnosticsCommands[] = {
  emberCommandEntryActionWithDetails("child-table", printChildTable, "", "Prints out the entries in the stack's child table.", NULL),
  emberCommandEntryActionWithDetails("neighbor-table", printNeighborTable, "", "Prints out the entries in the stack's neighbor table.", NULL),
  emberCommandEntryActionWithDetails("route-table", printRouteTable, "", "Prints out the entries in the stack's route table.", NULL),
  emberCommandEntryActionWithDetails("info", printInfo, "", "Prints out general information about the state of the stack.", NULL),
  emberCommandEntryTerminator()
};

PGM_P pluginAddressTableRemoveCommandArguments[] = {
  "Entry to be removed.",
  NULL
};

PGM_P pluginAddressTableAddCommandArguments[] = {
  "Entry to be added.",
  NULL
};

PGM_P pluginAddressTableLookupCommandArguments[] = {
  "Entry to be looked up.",
  NULL
};

EmberCommandEntry pluginAddressTableCommands[] = {
  emberCommandEntryActionWithDetails("remove", emberAfPluginAddressTableRemoveCommand, "b", "Remove an entry from the address table.", pluginAddressTableRemoveCommandArguments),
  emberCommandEntryActionWithDetails("add", emberAfPluginAddressTableAddCommand, "b", "Add an entry to the address table.", pluginAddressTableAddCommandArguments),
  emberCommandEntryActionWithDetails("lookup", emberAfPluginAddressTableLookupCommand, "b", "Lookup an entry in the address table.", pluginAddressTableLookupCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginIdentifyCommands[] = {
  emberCommandEntryActionWithDetails("print", emAfPluginIdentifyCliPrint, "", "Print which endpoints are reporting.", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry pluginConcentratorCommands[] = {
  emberCommandEntryActionWithDetails("stop", emberAfPluginConcentratorStopDiscovery, "", "Stops the periodic broadcast of MTORRs", NULL),
  emberCommandEntryActionWithDetails("status", emberAfPluginConcentratorStatus, "", "Prints current status and configured parameters of the concentrator", NULL),
  emberCommandEntryActionWithDetails("start", emberAfPluginConcentratorStartDiscovery, "", "Starts the periodic broadcast of MTORRs", NULL),
  emberCommandEntryActionWithDetails("print-table", emberAfPluginConcentratorPrintSourceRouteTable, "", "Print the source route table.", NULL),
  emberCommandEntryActionWithDetails("agg", emberAfPluginConcentratorAggregationCommand, "", "(Requires Concentrator Support to be enabled on this devic ...", NULL),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTablePluginCommands[] = {
  emberCommandEntrySubMenu("concentrator", pluginConcentratorCommands, ""),
  emberCommandEntrySubMenu("identify", pluginIdentifyCommands, ""),
  emberCommandEntrySubMenu("address-table", pluginAddressTableCommands, ""),
  emberCommandEntrySubMenu("stack-diagnostics", pluginStackDiagnosticsCommands, ""),
  emberCommandEntrySubMenu("ota-server", pluginOtaServerCommands, ""),
  emberCommandEntrySubMenu("button-joining", pluginButtonJoiningCommands, ""),
  emberCommandEntrySubMenu("reporting", pluginReportingCommands, ""),
  emberCommandEntrySubMenu("poll-control-client", pluginPollControlClientCommands, ""),
  emberCommandEntrySubMenu("ota-storage-common", pluginOtaStorageCommonCommands, ""),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTablePrintCommands[] = {
  emberCommandEntryActionWithDetails("time", printTimeCommand, "", "Print out the time information", NULL),
  emberCommandEntryActionWithDetails("attr", emberAfPrintAttributeTable, "", "Print the attribute table.", NULL),
  emberCommandEntryTerminator()
};

PGM_P securityMfgTokenSetCommandArguments[] = {
  "",
  "",
  NULL
};

EmberCommandEntry securityMfgTokenCommands[] = {
  emberCommandEntryActionWithDetails("get", getSetMfgToken, "", "", NULL),
  emberCommandEntryActionWithDetails("set", getSetMfgToken, "wv", "", securityMfgTokenSetCommandArguments),
  emberCommandEntryTerminator()
};

EmberCommandEntry emberCommandTableSecurityCommands[] = {
  emberCommandEntrySubMenu("mfg-token", securityMfgTokenCommands, ""),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableKeysDeleteCommandArguments[] = {
  "index into the security key table",
  NULL
};

EmberCommandEntry emberCommandTableKeysCommands[] = {
  emberCommandEntryActionWithDetails("clear", keysClearCommand, "", "Clear all security keys", NULL),
  emberCommandEntryActionWithDetails("delete", keysDeleteCommand, "u", "Delete a security key from a given index", emberCommandTableKeysDeleteCommandArguments),
  emberCommandEntryActionWithDetails("print", keysPrintCommand, "", "Print all security keys out to the command line.", NULL),
  emberCommandEntryTerminator()
};

PGM_P emberCommandTableRawCommandArguments[] = {
  "two byte cluster id",
  "two byte short id of the time server",
  NULL
};

PGM_P emberCommandTableBsendCommandArguments[] = {
  "source endpoint to send a binding based message from",
  NULL
};

PGM_P emberCommandTableSendCommandArguments[] = {
  "short id of the device to send the message to",
  "The endpoint to send the message from",
  "The endpoint to send the message to",
  NULL
};

PGM_P emberCommandTableSendMulticastCommandArguments[] = {
  "group id of the multicast group to send the message to",
  "The endpoint to send the message from",
  NULL
};

PGM_P emberCommandTableEchoCommandArguments[] = {
  "boolean indicating whether to turn echo on (1) or off (0)",
  NULL
};

PGM_P emberCommandTableTimesyncCommandArguments[] = {
  "two byte short id of the time server",
  "source endpoint to send time sync from",
  "destination endpoint to expect response on",
  NULL
};

PGM_P emberCommandTableWriteCommandArguments[] = {
  "endpoint of the attribute to write",
  "cluster id of the attribute to write",
  "attribute id of the attribute to write",
  "direction mask of the attribute to write (client=0 or server=1)",
  "the attribute type as listed in the generated file attribute-type.h",
  "string of bytes you wish to write into the attribute table.",
  NULL
};

PGM_P emberCommandTableReadCommandArguments[] = {
  "endpoint of the attribute to read",
  "cluster id of the attribute to read",
  "attribute id of the attribute to read",
  "direction mask of the attribute to read (client=0 or server=1)",
  NULL
};

EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryActionWithDetails("raw", emAfCliRawCommand, "vb", "Creates a message by specifying the raw byte ...", emberCommandTableRawCommandArguments),
  emberCommandEntryActionWithDetails("bsend", emAfCliBsendCommand, "u", "send using a binding based on the clusterId in the globalApsFrame and  ...", emberCommandTableBsendCommandArguments),
  emberCommandEntryActionWithDetails("send", emAfCliSendCommand, "vuu", "Send a pre-buffered message from a given endpoint to an endpoint on a  ...", emberCommandTableSendCommandArguments),
  emberCommandEntrySubMenu("keys", emberCommandTableKeysCommands, ""),
  emberCommandEntryActionWithDetails("libs", printAllLibraryStatus, "", "Lists which optional libraries of the stack are implemented on this de ...", NULL),
  emberCommandEntryActionWithDetails("send_multicast", emAfCliSendCommand, "vu", "Send a pre-buffered multicast message to a given group id from a given ...", emberCommandTableSendMulticastCommandArguments),
  emberCommandEntrySubMenu("security", emberCommandTableSecurityCommands, ""),
  emberCommandEntryActionWithDetails("counters", emAfCliCountersCommand, "", "Prints out values for tracked stack counters", NULL),
  emberCommandEntryActionWithDetails("echo", echoCommand, "u", "Turns echo on the command line on or off depending on the argument", emberCommandTableEchoCommandArguments),
  emberCommandEntrySubMenu("print", emberCommandTablePrintCommands, ""),
  emberCommandEntrySubMenu("plugin", emberCommandTablePluginCommands, ""),
  emberCommandEntrySubMenu("endpoint", emberCommandTableEndpointCommands, ""),
  emberCommandEntrySubMenu("network", emberCommandTableNetworkCommands, ""),
  emberCommandEntryActionWithDetails("version", emAfCliVersionCommand, "", "Shows the version of the software", NULL),
  emberCommandEntryActionWithDetails("info", emAfCliInfoCommand, "", "Gives information about the local node", NULL),
  emberCommandEntrySubMenu("debugprint", emberCommandTableDebugprintCommands, ""),
  emberCommandEntryActionWithDetails("help", helpCommand, "", "Prints out the cli command options for the device", NULL),
  emberCommandEntryActionWithDetails("timesync", emAfCliTimesyncCommand, "vuu", "This sends a read attr for the time of the device specifie ...", emberCommandTableTimesyncCommandArguments),
  emberCommandEntrySubMenu("zcl", emberCommandTableZclCommands, ""),
  emberCommandEntryActionWithDetails("write", emAfCliWriteCommand, "uvvuub", "Write an attribute value into the local attribute table", emberCommandTableWriteCommandArguments),
  emberCommandEntryActionWithDetails("reset", resetCommand, "", "resets the device", NULL),
  emberCommandEntryActionWithDetails("read", emAfCliReadCommand, "uvvu", "Read an attribute from the local attribute tabl ...", emberCommandTableReadCommandArguments),
  emberCommandEntrySubMenu("changekey", emberCommandTableChangekeyCommands, ""),
  emberCommandEntrySubMenu("zdo", emberCommandTableZdoCommands, ""),
  emberCommandEntrySubMenu("option", emberCommandTableOptionCommands, ""),
  emberCommandEntrySubMenu("interpan", emberCommandTableInterpanCommands, ""),
  emberCommandEntryTerminator()
};



