// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Color control cluster
 * application framework plugin.
 * @{
 */


/** @brief Is Color Supported
 *
 * This function will be called to determine whether a color is supported by a
 * device. The color will be specified by hue and saturation.
 *
 * @param hue   Ver.: always
 * @param saturation   Ver.: always
 */
boolean emberAfPluginColorControlIsColorSupportedCallback(int8u hue,
                                                          int8u saturation);



/** @} END addtogroup */
