// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Door Lock server
 * cluster application framework plugin.
 * @{
 */


/** @brief Activate Door Lock
 *
 * This function is provided by the door lock server plugin. It is
 *
 * @param activate True if the lock should move to the locked position, false
 * if it should move to the unlocked position  Ver.: always
 */
boolean emberAfPluginDoorLockServerActivateDoorLockCallback(boolean activate);



/** @} END addtogroup */
