// This file is generated by AppBuilder. Please do not edit manually.
// 
//

// Enclosing macro to prevent multiple inclusion
#ifndef __EMBER_AFHAL_CALLBACK_PROTOTYPES__
#define __EMBER_AFHAL_CALLBACK_PROTOTYPES__


/**
 * @addtogroup halCallback Application Framework V2 hal callback interface Reference
 * This header provides hal callback function prototypes to interface the
 * developer's application code with the Ember Application Framework.
 * @{
 */


#include "app/framework/include/af-types.h"


/** @name Hal Related Callbacks */
// @{
/** @brief emberAfHalButtonIsrCallback
 *
 *
 */
// Hal Button ISR Callback
// This callback is called by the framework whenever a button is pressed on the 
// device. This callback is called within ISR context.
void emberAfHalButtonIsrCallback(int8u button, int8u state);

/** @} END addtogroup */
#endif // __EMBER_AFHAL_CALLBACK_PROTOTYPES__
