// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Health Care 11073
 * Protocol Tunnel application framework plugin.
 * @{
 */




/** @} END addtogroup */
