// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Identify cluster
 * application framework plugin.
 * @{
 */


/** @brief Start Feedback
 *
 * This function is called by the Identify plugin when identification begins.
 * It informs the Identify Feedback plugin that it should begin providing its
 * implemented feedback functionality (e.g. LED blinking, buzzer sounding,
 * etc.) until the Identify plugin tells it to stop. The identify time is
 * purely a matter of informational convenience; this plugin does not need to
 * know how long it will identify (the Identify plugin will perform the
 * necessary timekeeping.)
 *
 * @param endpoint The identifying endpoint  Ver.: always
 * @param identifyTime The identify time  Ver.: always
 */
void emberAfPluginIdentifyStartFeedbackCallback(int8u endpoint,
                                                int16u identifyTime);

/** @brief Stop Feedback
 *
 * This function is called by the Identify plugin when identification is
 * finished. It tells the Identify Feedback plugin to stop providing its
 * implemented feedback functionality.
 *
 * @param endpoint The identifying endpoint  Ver.: always
 */
void emberAfPluginIdentifyStopFeedbackCallback(int8u endpoint);



/** @} END addtogroup */
