// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Interpan Plugin
 * application framework plugin.
 * @{
 */


/** @brief Pre Message Received
 *
 * This function is called by the Interpan plugin when an interpan message is
 * received but has not yet been handled by the plugin or the framework.  The
 * application should return TRUE if the message was handled.
 *
 * @param header   Ver.: always
 * @param msgLen   Ver.: always
 * @param message   Ver.: always
 */
boolean emberAfPluginInterpanPreMessageReceivedCallback(const EmberAfInterpanHeader * header,
                                                        int8u msgLen,
                                                        int8u * message);



/** @} END addtogroup */
