// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the OTA POSIX Filesystem
 * Storage Module application framework plugin.
 * @{
 */




/** @} END addtogroup */
