// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the OTA Simple Storage
 * EEPROM Driver application framework plugin.
 * @{
 */


/** @brief Erase Complete
 *
 * This is called when an EEPROM erase operation has completed.
 *
 * @param success The result of the erase operation.  Ver.: always
 */
void emberAfPluginOtaStorageSimpleEepromEraseCompleteCallback(boolean success);



/** @} END addtogroup */
