// This file is generated by AppBuilder. Please do not edit manually.
// 
//

// Enclosing macro to prevent multiple inclusion
#ifndef __EMBER_AF_STACK_HANDLERS__
#define __EMBER_AF_STACK_HANDLERS__


// Macros required for implemented stack handlers.


#ifdef EZSP_HOST
#else // ! EZSP_HOST
#endif // EZSP_HOST
#endif // __EMBER_AF_STACK_HANDLERS__
