// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Standalone Bootloader
 * Client application framework plugin.
 * @{
 */


/** @brief Allow Incoming Message
 *
 * Allows the application to control whether the plugin can respond to
 * incoming bootload messages.
 *
 * @param sourceEui64 The EUI64 of the sending node.  Ver.: always
 * @param command The incoming command ID  Ver.: always
 */
boolean emberAfPluginStandaloneBootloaderClientAllowIncomingMessageCallback(EmberEUI64 sourceEui64,
                                                                            int8u command);

/** @brief Allow Bootload Launch
 *
 * This function is a callback when the client is being told to launch the
 * standalone bootloader.  This is done after authentication has completed
 * successfully.
 *
 * @param sourceEui64 The EUI64 of the node requesting the bootload.  Ver.:
 * always
 */
boolean emberAfPluginStandaloneBootloaderClientAllowBootloadLaunchCallback(EmberEUI64 sourceEui64);



/** @} END addtogroup */
