// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Standalone Bootloader
 * Common  application framework plugin.
 * @{
 */


/** @brief Incoming Message
 *
 * Indicates an Ember Bootload message has been received by the Standalone
 * Bootloader Common plugin.
 *
 * @param longId The sender's EUI64 address  Ver.: always
 * @param length The length of the incoming message.  Ver.: always
 * @param message The array of bytes for the message.  Ver.: always
 */
boolean emberAfPluginStandaloneBootloaderCommonIncomingMessageCallback(EmberEUI64 longId,
                                                                       int8u length,
                                                                       int8u* message);



/** @} END addtogroup */
