// This file is generated by AppBuilder. Please do not edit manually.
// 
//

/**
 * @addtogroup callback Application Framework V2 callback interface Reference
 * This header provides callback function prototypes for the Standalone Bootloader
 * Server application framework plugin.
 * @{
 */


/** @brief Query Response
 *
 * Allows the application to control whether the plugin can respond to
 * incoming bootload messages.
 *
 * @param queryWasBroadcast Boolean indicating whether the query was broadcast
 * or unicast  Ver.: always
 * @param queryData A data structure providing the details about the local
 * device's bootloader.  Ver.: always
 */
void emberAfPluginStandaloneBootloaderServerQueryResponseCallback(boolean queryWasBroadcast,
                                                                  const EmberAfStandaloneBootloaderQueryResponseData* queryData);

/** @brief Finished
 *
 * Notifies the application when the standalone bootload has completed,
 * successfully or otherwise.
 *
 * @param success Boolean indicating the success or failure of the bootload. 
 * Ver.: always
 */
void emberAfPluginStandaloneBootloaderServerFinishedCallback(boolean success);



/** @} END addtogroup */
