obj-${CONFIG_WEMO_GPIO_SNS}		+= sns_gpio.o 
obj-${CONFIG_WEMO_GPIO_BABYMON}		+= babymon_gpio.o
obj-${CONFIG_WEMO_GPIO_INSIGHT} 	+= insight_gpio.o
obj-${CONFIG_WEMO_GPIO_GUARDIAN} 	+= guardian_gpio.o
obj-${CONFIG_WEMO_GPIO_CROCKPOT}	+= crockpot_gpio.o

sns_gpio-objs 		:= ralink_gpio.o sns.o
babymon_gpio-objs 	:= ralink_gpio.o babymon.o
insight_gpio-objs 	:= ralink_gpio.o insight.o
guardian_gpio-objs 	:= ralink_gpio.o guardian.o
crockpot_gpio-objs 	:= ralink_gpio.o crockpot.o

